const AUDIT_ACTIONS = Object.freeze({
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  TOKEN_REFRESHED: "TOKEN_REFRESHED",
  LOGOUT: "LOGOUT",

  RECEPTIONIST_CREATED: "RECEPTIONIST_CREATED",
  RECEPTIONIST_UPDATED: "RECEPTIONIST_UPDATED",

  DOCTOR_CREATED: "DOCTOR_CREATED",
  DOCTOR_UPDATED: "DOCTOR_UPDATED",

  SCHEDULE_CREATED: "SCHEDULE_CREATED",
  SCHEDULE_UPDATED: "SCHEDULE_UPDATED",
  SCHEDULE_DEACTIVATED: "SCHEDULE_DEACTIVATED",
});

module.exports = AUDIT_ACTIONS;
